# Generated by Django 5.1.5 on 2025-02-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_car_user_car_parchased_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='parchased_by',
            new_name='purchased_by',
        ),
    ]
